### ISSUE TITLE
wrap all results in Either

### ISSUE THREAD

**Issue by khlrb** [riottracker/RtMidi#2]
first step: marshal error messages

**Comment by ejconlon** [comment]
As you have seen, `guardError` is now called anywhere there might be an error from the backend, and it throws exceptions with error messages. It's not clear to me without auditing exactly which errors indicate it's safe to re-use the device again, so I'm inclined to say "let it crash and don't re-use it!" That said, it's always possible to `try @Error`.

(I'm closing to clean up, please re-open if you want to discuss further.)
